# Example data source config file: https://grafana.com/docs/grafana/latest/administration/provisioning/?utm_source=grafana_ds_list#example-data-source-config-file

# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
#deleteDatasources:
#  - name: Graphite
#    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  - access: proxy
    basicAuth: 'false'
    database: ''
    id: '2'
    isDefault: 'false'
    jsonData: {}
    name: Prometheus
    orgId: '1'
    readOnly: 'true'
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    typeName: Prometheus
    uid: P111D79A3F645F221
    url: http://prometheus:9090
    user: ''
  - access: proxy
    basicAuth: 'true'
    database: 'koda'
    id: '1'
    isDefault: 'false'
    jsonData:
      connMaxLifetime: 14400
      database: koda
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      sslmode: disable
      user: foo
      password: foo
    secureJsonData:
      password: foo
    name: Sidekick postgres database
    orgId: '1'
    readOnly: 'false'
    type: grafana-postgresql-datasource
    typeLogoUrl: public/app/plugins/datasource/grafana-postgresql-datasource/img/postgresql_logo.svg
    typeName: PostgreSQL
#    uid: fdgdsv9fu5kaoa
    url: koda_postgres:5432
#    url: localhost:5432
    user: foo

